### PR TITLE
Add a delay between OpenTDB API requests and retry if the API cannot be reached

### PR DESCRIPTION
**Pull request by TheOpponent**
As of December 2023, there is a limit of 1 API request per IP every 5 seconds. This pull request handles the rate limit response code and adds a delay between requests.

### CODE REVIEW

**Comment by TheOpponent** [comment]
I changed the number of questions to request from 10 to 50 because of the delay, but the API doesn't respond with fewer questions if there are fewer questions remaining than the requested amount.

**Comment by EverdredIIDX** [comment]
Thanks for submitting this. Was the closure a mistake?

**Comment by TheOpponent** [comment]
I found that this patch has some major issues after I posted it that I wanted to fix. Please delete this pull request and I will submit another when I make corrections.

**Comment by EverdredIIDX** [comment]
Sounds good. thanks!

**Pull request closed without merging**
